spring:
  profiles:
    include: common

  # DB
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product?useUnicode=yes&characterEncoding=UTF-8
    connection-properties:
    username: product_user
    password: product_user
    connection-test-query: SELECT 1
    test-while-idle: true
    test-on-borrow: true
    validation-query: SELECT 1
    validation-interval: 34
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  # thymeleaf
  thymeleaf:
    cache: false

# Security
security:
  basic:
    enabled: false

# Tomcat
server:
  port: 8080
  tomcat:
    access-log-enabled: true
    access-log-pattern: "%h %l %u %t '%r' %s %b %D '%{User-Agent}i'"
    basedir: /tmp

# AppConfig
appconfig:
  appPath:
  appUrl: http://localhost:8080
